How to download candidate data

In [4]:
A_site = ["Cs", "Rb", "K"]
B_site = ["Pb", "Sn", "Ge"]
X_site = ["Cl", "Br", "I"]

In [ ]:
# for less candidates

candidates = []

for A in A_site:
    for B in B_site:
        for X in X_site:
            formula = A + B + X + "3"
            candidates.append(formula)

print("Total candidates:", len(candidates))
candidates[:10]

Total candidates: 27

['CsPbCl3',
 'CsPbBr3',
 'CsPbI3',
 'CsSnCl3',
 'CsSnBr3',
 'CsSnI3',
 'CsGeCl3',
 'CsGeBr3',
 'CsGeI3',
 'RbPbCl3']

In [ ]:
##fraction of candidates with "Cs" in A-site so we will not use this data for training
# code for 1000 candidates with random mixing ratios
import random

A_site = ["Cs", "Rb", "K"]
B_site = ["Pb", "Sn", "Ge"]
X_site = ["Cl", "Br", "I"]

candidates = set()

while len(candidates) < 1000:
    
    A = random.choice(A_site)
    B = random.choice(B_site)
    
    X1, X2 = random.sample(X_site, 2)
    
    # Random mixing ratio
    ratio = round(random.uniform(0.1, 0.9), 2)
    
    formula = f"{A}{B}({X1}{ratio}{X2}{1-ratio})3"
    
    candidates.add(formula)

candidates = list(candidates)

print("Generated candidates:", len(candidates))
candidates[:10]

Generated candidates: 1000

['KPb(Br0.11I0.89)3',
 'RbGe(Br0.44I0.56)3',
 'KGe(I0.88Cl0.12)3',
 'CsGe(I0.15Br0.85)3',
 'CsPb(Br0.21Cl0.79)3',
 'CsGe(Cl0.37Br0.63)3',
 'CsSn(I0.31Br0.69)3',
 'CsGe(Cl0.86I0.14)3',
 'KGe(I0.54Cl0.45999999999999996)3',
 'CsGe(Br0.45Cl0.55)3']

In [ ]:
import pandas as pd

candidate_df = pd.DataFrame(candidates, columns=["composition"])

candidate_df.head()

##fraction of candidates with "Cs" in A-site so we will not use this data for training

           composition
0    KPb(Br0.11I0.89)3
1   RbGe(Br0.44I0.56)3
2    KGe(I0.88Cl0.12)3
3   CsGe(I0.15Br0.85)3
4  CsPb(Br0.21Cl0.79)3

In [10]:
A_site = ["Cs", "Rb", "K", "Na"]
B_site = ["Pb", "Sn", "Ge", "Bi"]
X_site = ["Cl", "Br", "I"]

candidates = []

for A in A_site:
    for B in B_site:
        for X in X_site:
            candidates.append(A + B + X + "3")

candidate_df = pd.DataFrame(candidates, columns=["composition"])

print("Total candidates:", len(candidate_df))

Total candidates: 48

In [12]:
candidate_df.tail()

   composition
43     NaGeBr3
44      NaGeI3
45     NaBiCl3
46     NaBiBr3
47      NaBiI3

In [13]:
from pymatgen.core import Composition
from matminer.featurizers.composition import ElementProperty

# Convert to pymatgen format
candidate_df["composition_obj"] = candidate_df["composition"].apply(Composition)

# Use Magpie features
featurizer = ElementProperty.from_preset("magpie")

candidate_df = featurizer.featurize_dataframe(candidate_df, "composition_obj")

print("Feature dataset ready")
candidate_df.head()

C:\Users\HP\AppData\Roaming\Python\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
ElementProperty: 100%|██████████| 48/48 [00:00<00:00, 174.11it/s]

Feature dataset ready

,composition,composition_obj,MagpieData minimum Number,MagpieData maximum Number,MagpieData range Number,MagpieData mean Number,MagpieData avg_dev Number,MagpieData mode Number,MagpieData minimum MendeleevNumber,MagpieData maximum MendeleevNumber,...,MagpieData range GSmagmom,MagpieData mean GSmagmom,MagpieData avg_dev GSmagmom,MagpieData mode GSmagmom,MagpieData minimum SpaceGroupNumber,MagpieData maximum SpaceGroupNumber,MagpieData range SpaceGroupNumber,MagpieData mean SpaceGroupNumber,MagpieData avg_dev SpaceGroupNumber,MagpieData mode SpaceGroupNumber
0,CsPbCl3,"(Cs, Pb, Cl)",17.0,82.0,65.0,37.6,24.72,17.0,5.0,94.0,...,0.0,0.0,0.0,0.0,64.0,229.0,165.0,129.2,78.24,64.0
1,CsPbBr3,"(Cs, Pb, Br)",35.0,82.0,47.0,48.4,16.08,35.0,5.0,95.0,...,0.0,0.0,0.0,0.0,64.0,229.0,165.0,129.2,78.24,64.0
2,CsPbI3,"(Cs, Pb, I)",53.0,82.0,29.0,59.2,9.12,53.0,5.0,96.0,...,0.0,0.0,0.0,0.0,64.0,229.0,165.0,129.2,78.24,64.0
3,CsSnCl3,"(Cs, Sn, Cl)",17.0,55.0,38.0,31.2,17.04,17.0,5.0,94.0,...,0.0,0.0,0.0,0.0,64.0,229.0,165.0,112.4,58.08,64.0
4,CsSnBr3,"(Cs, Sn, Br)",35.0,55.0,20.0,42.0,8.40,35.0,5.0,95.0,...,0.0,0.0,0.0,0.0,64.0,229.0,165.0,112.4,58.08,64.0

In [14]:
candidate_df.to_csv("candidate_features.csv", index=False)

print("Candidate feature dataset saved successfully")

Candidate feature dataset saved successfully

In [15]:
selected_features = [
    "composition",
    "MagpieData mean Electronegativity",
    "MagpieData mean AtomicWeight",
    "MagpieData mean CovalentRadius",
    "MagpieData mean NValence",
    "MagpieData mean MeltingT"
]

reduced_df = candidate_df[selected_features].copy()

reduced_df.head()

,composition,MagpieData mean Electronegativity,MagpieData mean AtomicWeight,MagpieData mean CovalentRadius,MagpieData mean NValence,MagpieData mean MeltingT
0,CsPbCl3,2.520,89.292890,139.2,10.0,283.400
1,CsPbBr3,2.400,115.963490,150.0,16.0,339.920
2,CsPbI3,2.220,144.163772,161.4,16.0,412.550
3,CsSnCl3,2.446,71.594890,137.8,7.2,264.294
4,CsSnBr3,2.326,98.265490,148.6,13.2,320.814

In [16]:
import math
from pymatgen.core import Composition, Element

def compute_tolerance_factor(formula):
    try:
        comp = Composition(formula)
        elems = list(comp.elements)
        
        if len(elems) != 3:
            return None
        
        # crude assignment (A,B,X)
        A, B, X = elems
        
        rA = Element(str(A)).atomic_radius or 1
        rB = Element(str(B)).atomic_radius or 1
        rX = Element(str(X)).atomic_radius or 1
        
        t = (rA + rX) / (math.sqrt(2) * (rB + rX))
        return t
    
    except:
        return None

reduced_df["tolerance_factor"] = reduced_df["composition"].apply(compute_tolerance_factor)

In [17]:
reduced_df.head()

,composition,MagpieData mean Electronegativity,MagpieData mean AtomicWeight,MagpieData mean CovalentRadius,MagpieData mean NValence,MagpieData mean MeltingT,tolerance_factor
0,CsPbCl3,2.520,89.292890,139.2,10.0,283.400,0.909137
1,CsPbBr3,2.400,115.963490,150.0,16.0,339.920,0.898865
2,CsPbI3,2.220,144.163772,161.4,16.0,412.550,0.883883
3,CsSnCl3,2.446,71.594890,137.8,7.2,264.294,1.039014
4,CsSnBr3,2.326,98.265490,148.6,13.2,320.814,1.019866

In [18]:
reduced_df = reduced_df.rename(columns={
    "MagpieData mean Electronegativity": "electronegativity_mean",
    "MagpieData mean AtomicWeight": "atomic_weight_mean",
    "MagpieData mean CovalentRadius": "atomic_radius_mean",
    "MagpieData mean NValence": "valence_electrons_mean",
    "MagpieData mean MeltingT": "melting_temp_mean",
    "tolerance_factor": "tolerance_factor"
})

reduced_df.head()

,composition,electronegativity_mean,atomic_weight_mean,atomic_radius_mean,valence_electrons_mean,melting_temp_mean,tolerance_factor
0,CsPbCl3,2.520,89.292890,139.2,10.0,283.400,0.909137
1,CsPbBr3,2.400,115.963490,150.0,16.0,339.920,0.898865
2,CsPbI3,2.220,144.163772,161.4,16.0,412.550,0.883883
3,CsSnCl3,2.446,71.594890,137.8,7.2,264.294,1.039014
4,CsSnBr3,2.326,98.265490,148.6,13.2,320.814,1.019866

In [19]:
reduced_df.to_csv("candidate_clean_features.csv", index=False)

print("Clean dataset saved")

Clean dataset saved